version: "3"

services:
  app:
    container_name: uploader-v2-app
    build:
      context: .
      dockerfile: ./dev/go/Dockerfile
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./src:/uploader-v2
      - go_modules:/go/pkg
    working_dir: /uploader-v2
    networks:
      uploader-v2:
        ipv4_address: 10.2.0.10
    environment:
      - GO111MODULE=on
  minio:
    container_name: uploader-v2-minio
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    command: minio server /data --console-address :9001
    volumes:
      - minio:/data
    networks:
      uploader-v2:
        ipv4_address: 10.2.0.50
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  go_modules:
  minio:

networks:
  uploader-v2:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
