version: "3"

services:
  go:
    build:
      context: .
      dockerfile: ./go/Dockerfile
    volumes:
      - .:/workspace:cached
      - go_modules:$HOME/go/pkg
    ports:
      - 8080:8080
    tty: true
    environment:
      - GO111MODULE=on
      - GOMODCACHE=/home/vscode/go/pkg/mod
      - GOPATH=/home/vscode/go

  # terraform:
  #   container_name: slack-download-url-generator-terraform
  #   build:
  #     context: ./terraform
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/workspace

volumes:
  go_modules: