version: "3"

services:
  go:
    container_name: uploader-v2-go
    build:
      context: ./go
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - go_modules:$HOME/go/pkg
    ports:
      - 8080:8080
    tty: true
    environment:
      - GO111MODULE=on
      - GOMODCACHE=/home/vscode/go/pkg/mod
      - GOPATH=/home/vscode/go
    command: air -c /workspace/.air.toml

  minio:
    container_name: uploader-v2-minio
    image: minio/minio:latest
    volumes:
      - minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    command: minio server /data --console-address :9001

  terraform:
    container_name: uploader-v2-terraform
    build:
      context: ./terraform
      dockerfile: Dockerfile
    volumes:
      - .:/workspace

volumes:
  go_modules:
  minio: