name: AWS Lambda Deploy 
on:
  pull_request:
    paths:
      - 'go/**'
    branches:
      - main
    types:
      - closed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS CLI install
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: AWS set Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - run: aws sts get-caller-identity

      - name: lambda update
        run: |
          cd go && zip -r package.zip ./*
          aws lambda update-function-code --function-name slack-download-url-generator-prod-app --zip-file fileb://package.zip --publish